"""Módulo que fornece as configurações do jogo."""

# __SCREEN__
# SCREENSIZEWIDTH = 400
# SCREENSIZEHEIGHT = 170
SCREENSIZEWIDTH = 1200
SCREENSIZEHEIGHT = 510
# SCREENSIZEWIDTH = 800
# SCREENSIZEHEIGHT = 340


# __FPS__
FPS = 60

# __MUSIC__
STAGE_VOLUME = 0.1
FX_VOLUME = 0.5
LOOP = -1

# __PHYSICS
GRAVITY = 150.0
INITIAL_SPEED = 88.0
MAX_SPEED = 90.0
ACCELERATION = 1.5

# Supondo que você tenha um valor de chance
CRITICAL_HIT_CHANCE = 5  # 10% de chance
